server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillsync
    username: ${env.SPRING_DATASOURCE_USERNAME}
    password: ${env.SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: ${env.JWT_SECRET}
  expiration: ${env.JWT_EXPIRATION}


