spring:
  datasource:
    url: jdbc:postgresql://skillsync-database.c8fui4oca2gt.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: aOmELuxe7YyGnpQ5hRcR
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  h2:
    console:
      enabled: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}
  expiration: ${JWT_EXPIRATION:604800000} # 7 days in milliseconds

# Server Configuration
server:
  port: ${PORT:8080}

# Logging Configuration
logging:
  level:
    com.skillsync: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
