server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/skillsync
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true


jwt:
  secret: ${env.JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${env.JWT_EXPIRATION:604800000}


